// Command docprobe renders every corpus input with the vendored Python and
// stores the resulting `.typ`, `.md` and `.html` under
// internal/renderer/document/testdata/documents/<case>/, beside the input they
// came from.
//
// **This is the gate iterations 9 and 11 end at** (spec 009 §6, spec 011 §5):
// the Go renderer's output has to be byte-identical to these. It is a differential rather than a
// read of `testdata/golden`, for one reason — the goldens were generated on a
// particular day and carry that date in the preamble and the top note, while
// this pins `settings.current_date` so both sides are reproducible.
//
// **What this tool cannot check.** Only the cases it renders, and nothing here
// covers the Markdown or HTML documents.
//
// Twenty-two of the forty-three corpus cases are skipped. Nineteen have no
// `cv.yaml`: the `cli_*` and `err_*` cases, and — worth naming, because the
// earlier wording implied otherwise — `new_default`, `new_typst_templates` and
// `sample_entries`, whose input is `John_Doe_CV.yaml`. The first two carry the
// canonical sample CV, which nothing in this repo renders differentially. Three
// more are skipped because upstream itself rejects them (`err_empty_yaml`,
// `err_not_yaml`, `err_unknown_theme`).
//
// A Go failure cannot produce a skip: this tool never runs Go code.
//
// The fixture is GENERATED and is NEVER hand-written or hand-edited
// (AGENTS.md §10.1); this program is its only author. It is not part of
// testdata/golden, so regenerating it does not change the parity contract and
// needs no special approval.
//
// Usage:
//
//	go run ./tools/docprobe    # or: just docprobe
package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/nonamecat19/rendercv-go/internal/conformance/workroot"
)

const (
	upstreamDir = "third_party/rendercv"
	outDir      = "internal/renderer/document/testdata/documents"

	// CurrentDate is what every case is rendered with, so the preamble's
	// `datetime(...)` and the top note's month are the same on both sides and on
	// every day. It is the reference date the port's own tests already use.
	CurrentDate = "2025-03-05"
)

// extraCases are documents the corpus does not contain, kept here so they are
// generated by the same path as the corpus ones — a hand-placed fixture would be
// deleted by the next run and is forbidden outright (AGENTS.md §10.1).
//
// Each exists because a verifier found the port wrong on it and the corpus could
// not see it:
//
//   - `design_null_column`: `degree_column: null` is the one nullable design
//     field with a non-null default, and the port emitted the default instead of
//     omitting the column.
//   - `locale_overrides`: seven of `locale.Resolve`'s nine override branches
//     were reached by no test at all. They were correct; nothing pinned them.
//   - `header_photo`: every corpus `cv.yaml` writes `photo:` with a **null**
//     value, so nothing exercised the header's `#grid`. The port emitted a bare
//     name where upstream emits the whole two-column grid.
var extraCases = map[string]string{
	"header_photo": `cv:
  name: John Doe
  photo: images/me.png
  email: john@example.com
  sections:
    education:
      - institution: MIT
        area: CS
`,

	"locale_overrides": `cv:
  name: John Doe
  sections:
    education:
      - institution: MIT
        area: CS
        start_date: 2000-09
        end_date: present
      - institution: Singular
        area: One of each
        start_date: 2020-01
        end_date: 2021-02
      - institution: One month
        area: The singular month
        start_date: 2020-01
        end_date: 2020-01
locale:
  language: french
  last_updated: "Mis à jour le"
  month: MONTH1
  months: MONTHN
  year: YEAR1
  years: YEARN
  present: aujourd'hui
  month_abbreviations: [A01, A02, A03, A04, A05, A06, A07, A08, A09, A10, A11, A12]
  month_names: [N01, N02, N03, N04, N05, N06, N07, N08, N09, N10, N11, N12]
  phrases:
    degree_with_area: DEGREE en AREA
design:
  theme: classic
  templates:
    single_date: MONTH_NAME (MONTH_ABBREVIATION) YEAR
  sections:
    show_time_spans_in: [Education]
`,

	"design_null_column": `cv:
  name: John Doe
  sections:
    education:
      - institution: MIT
        area: CS
        degree: BS
design:
  theme: classic
  templates:
    education_entry:
      degree_column:
`,

	// wave_c_emphasis is spec 011 §11: the four shapes Wave C's emphasis and
	// link-destination fix changed the `.html` for. `***bold italic***` is the
	// highest-reach one — it is how a CV bullet actually writes bold-italic, and
	// was wrong end-to-end before T9. The `.md` must be byte-identical to what
	// it was before Wave C; only the `.html` moves, and only on these four
	// lines.
	"wave_c_emphasis": `cv:
  name: John Doe
  email: john@example.com
  sections:
    experience:
      - company: Acme
        position: Engineer
        start_date: 2020-01
        end_date: present
        summary: A ***bold italic*** lead who wrote _a __b__ c_ in reviews.
        highlights:
          - Shipped *a **b** c* across every service
          - Won the [Best Paper Award](https://example.com/my paper.pdf)
`,
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "docprobe:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := repoRoot()
	if err != nil {
		return err
	}

	corpusDir := filepath.Join(workroot.Root, "run")
	cases, err := os.ReadDir(corpusDir)
	if err != nil {
		return fmt.Errorf("reading the corpus (run `just golden` first?): %w", err)
	}

	target := filepath.Join(root, outDir)
	if err := os.RemoveAll(target); err != nil {
		return err
	}

	var rendered, skipped []string
	for _, entry := range cases {
		if !entry.IsDir() {
			continue
		}
		name := entry.Name()

		input := filepath.Join(corpusDir, name, "cv.yaml")
		if _, err := os.Stat(input); err != nil {
			skipped = append(skipped, name+" (no cv.yaml)")
			continue
		}

		typ, err := renderCase(root, input)
		if err != nil {
			skipped = append(skipped, name+" ("+err.Error()+")")
			continue
		}

		dir := filepath.Join(target, name)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
		raw, err := os.ReadFile(input)
		if err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(dir, "cv.yaml"), raw, 0o644); err != nil {
			return err
		}
		if err := writeArtifacts(dir, typ); err != nil {
			return err
		}
		rendered = append(rendered, name)
	}

	for name, document := range extraCases {
		input, err := writeExtra(name, document)
		if err != nil {
			return err
		}
		typ, err := renderCase(root, input)
		if err != nil {
			return fmt.Errorf("extra case %s: %w", name, err)
		}

		dir := filepath.Join(target, name)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(dir, "cv.yaml"), []byte(document), 0o644); err != nil {
			return err
		}
		if err := writeArtifacts(dir, typ); err != nil {
			return err
		}
		// The fixture has to carry the photo too: the conformance test validates
		// the input, and `cv.photo`'s existence check runs there as well.
		if err := copyImages(filepath.Dir(input), dir); err != nil {
			return err
		}
		rendered = append(rendered, name)
	}

	sort.Strings(rendered)
	sort.Strings(skipped)
	fmt.Printf("rendered %d cases into %s\n", len(rendered), outDir)
	for _, name := range skipped {
		fmt.Println("  skipped", name)
	}
	if len(rendered) == 0 {
		return fmt.Errorf("no case rendered; the fixture would be empty")
	}
	return nil
}

// writeExtra materializes one extra case's document so renderCase can treat it
// exactly like a corpus input.
func writeExtra(name, document string) (string, error) {
	dir, err := os.MkdirTemp("", "docprobe-extra-"+name+"-")
	if err != nil {
		return "", err
	}

	// `cv.photo` is an **existence-checked** path, so a case that names one has
	// to have one. The bytes are a PNG header and nothing reads them: neither
	// side decodes the image, and no case here compiles the Typst.
	if strings.Contains(document, "images/me.png") {
		images := filepath.Join(dir, "images")
		if err := os.MkdirAll(images, 0o755); err != nil {
			return "", err
		}
		png := []byte{0x89, 'P', 'N', 'G', '\r', '\n', 0x1a, '\n'}
		if err := os.WriteFile(filepath.Join(images, "me.png"), png, 0o644); err != nil {
			return "", err
		}
	}

	path := filepath.Join(dir, "cv.yaml")
	return path, os.WriteFile(path, []byte(document), 0o644)
}

// renderCase runs the vendored CLI in a scratch directory, so the corpus's own
// working tree is never written to, and returns the one `.typ` it produced.
func renderCase(root, input string) (artifacts, error) {
	scratch, err := os.MkdirTemp("", "docprobe-")
	if err != nil {
		return artifacts{}, err
	}
	defer func() { _ = os.RemoveAll(scratch) }()

	raw, err := os.ReadFile(input)
	if err != nil {
		return artifacts{}, err
	}
	copied := filepath.Join(scratch, "cv.yaml")
	if err := os.WriteFile(copied, raw, 0o644); err != nil {
		return artifacts{}, err
	}

	// `cv.photo` is resolved **relative to the input file** and its existence is
	// checked, so a case that names one needs its `images/` beside the copy.
	if err := copyImages(filepath.Dir(input), scratch); err != nil {
		return artifacts{}, err
	}

	cmd := exec.Command(
		"uv", "run", "--frozen", "--all-extras",
		"rendercv", "render", copied,
		"-nopdf", "-nopng",
		"--settings.current_date", CurrentDate,
	)
	cmd.Dir = filepath.Join(root, upstreamDir)
	if out, err := cmd.CombinedOutput(); err != nil {
		return artifacts{}, fmt.Errorf("upstream rejected it: %s", firstLine(out))
	}

	out := artifacts{}
	for extension, target := range map[string]*[]byte{
		"typ": &out.typ, "md": &out.markdown, "html": &out.html,
	} {
		matches, err := filepath.Glob(
			filepath.Join(scratch, "rendercv_output", "*."+extension))
		if err != nil {
			return artifacts{}, err
		}
		if len(matches) != 1 {
			return artifacts{}, fmt.Errorf("produced %d .%s files", len(matches), extension)
		}
		raw, err := os.ReadFile(matches[0])
		if err != nil {
			return artifacts{}, err
		}
		*target = raw
	}
	return out, nil
}

// artifacts are the three text documents one render produces. The PDF and the
// PNGs are iteration 10's and are not generated at all — they are slow, and
// their bytes carry timestamps that could never be compared this way.
type artifacts struct {
	typ, markdown, html []byte
}

// writeArtifacts stores the three documents beside the input they came from.
func writeArtifacts(dir string, out artifacts) error {
	for name, content := range map[string][]byte{
		"expected.typ": out.typ, "expected.md": out.markdown, "expected.html": out.html,
	} {
		if err := os.WriteFile(filepath.Join(dir, name), content, 0o644); err != nil {
			return err
		}
	}
	return nil
}

// copyImages copies an `images/` directory beside the input, when there is one.
func copyImages(from, to string) error {
	entries, err := os.ReadDir(filepath.Join(from, "images"))
	if err != nil {
		return nil //nolint:nilerr // no images directory is the ordinary case
	}

	target := filepath.Join(to, "images")
	if err := os.MkdirAll(target, 0o755); err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		raw, err := os.ReadFile(filepath.Join(from, "images", entry.Name()))
		if err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(target, entry.Name()), raw, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func firstLine(out []byte) string {
	text := strings.TrimSpace(string(out))
	if index := strings.IndexByte(text, '\n'); index >= 0 {
		text = text[:index]
	}
	if len(text) > 120 {
		text = text[:120]
	}
	return text
}

func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod above %s", dir)
		}
		dir = parent
	}
}
