//go:build conformance

package rendercv_test

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/nonamecat19/rendercv-go/pkg/rendercv"
)

// TestTheLibraryProducesTheGoldenArtifacts is spec 016 §5.2.
//
// The point is not that the library works — the tests beside this one cover
// that. It is that the library produces **the same bytes the CLI does**, and
// the only way to state that mechanically is to compare against a golden, which
// was generated by the vendored Python and never by this port.
//
// Without it, the facade and the CLI could drift apart and every test in this
// package would still pass, because they would all be measuring the facade
// against itself. That is the failure mode plan §1.1 restructured the
// generators to prevent, and this is the check that it held.
func TestTheLibraryProducesTheGoldenArtifacts(t *testing.T) {
	// ats_minimal is chosen because it exercises the three text formats with no
	// theme, locale or overlay complications — anything that differs is the
	// facade's own doing.
	const (
		caseName = "ats_minimal"
		// The corpus inputs live in the vendored upstream, which is where the
		// conformance harness reads them from too (conformance.go:158).
		inputFile = "../../third_party/rendercv/scripts/ats_proof/corpus/baseline/minimal.yaml"
		goldenDir = "../../testdata/golden/" + caseName + "/files/rendercv_output"
	)

	source, err := os.ReadFile(inputFile)
	if err != nil {
		t.Fatalf("read the corpus input: %v", err)
	}

	// The case's own arguments, as the library expresses them: the CLI's
	// `--settings.current_date 2025-03-05` is a dotted override, and the input
	// path is what relative paths and the output folder resolve against.
	work := t.TempDir()
	inputPath := filepath.Join(work, "cv.yaml")
	if err := os.WriteFile(inputPath, source, 0o600); err != nil {
		t.Fatalf("stage the input: %v", err)
	}

	_, model, err := rendercv.Build(string(source), rendercv.BuildOptions{
		InputFilePath: inputPath,
		Overrides:     map[string]string{"settings.current_date": "2025-03-05"},
		// The PDF and the PNGs are compared by the parity suite, which can
		// check page geometry; this case is about the text artifacts.
		DontGeneratePDF: true,
		DontGeneratePNG: true,
	})
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	typstPath, err := rendercv.GenerateTypst(model)
	if err != nil {
		t.Fatalf("GenerateTypst: %v", err)
	}
	markdownPath, err := rendercv.GenerateMarkdown(model)
	if err != nil {
		t.Fatalf("GenerateMarkdown: %v", err)
	}
	htmlPath, err := rendercv.GenerateHTML(model, markdownPath)
	if err != nil {
		t.Fatalf("GenerateHTML: %v", err)
	}

	for _, artifact := range []struct{ produced, golden string }{
		{typstPath, filepath.Join(goldenDir, "Bob_Smith_CV.typ")},
		{markdownPath, filepath.Join(goldenDir, "Bob_Smith_CV.md")},
		{htmlPath, filepath.Join(goldenDir, "Bob_Smith_CV.html")},
	} {
		t.Run(filepath.Ext(artifact.golden), func(t *testing.T) {
			got, err := os.ReadFile(artifact.produced)
			if err != nil {
				t.Fatalf("read what the library wrote: %v", err)
			}
			want, err := os.ReadFile(artifact.golden)
			if err != nil {
				t.Fatalf("read the golden: %v", err)
			}
			if string(got) != string(want) {
				t.Errorf("%s differs from the golden:\n%s",
					filepath.Base(artifact.golden), firstDifference(string(got), string(want)))
			}
		})
	}
}

// firstDifference locates a byte diff and shows its neighbourhood.
//
// A bare byte count gives the rendercv-parity-debug playbook nothing to start
// from, which is what this reported before.
func firstDifference(got, want string) string {
	limit := min(len(got), len(want))
	at := limit
	for i := range limit {
		if got[i] != want[i] {
			at = i
			break
		}
	}

	line := 1 + strings.Count(got[:at], "\n")
	column := at - strings.LastIndex(got[:at], "\n")
	window := func(s string) string {
		from := max(at-40, 0)
		to := min(at+40, len(s))
		return strconv.Quote(s[from:to])
	}
	return fmt.Sprintf("  first difference at byte %d (line %d, column %d); %d bytes against %d\n  golden: %s\n  got:    %s",
		at, line, column, len(got), len(want), window(want), window(got))
}
