// Command localeprobe generates the locale catalog data from the submodule.
//
// **Generated, not transcribed** (`AGENTS.md` §10.1's spirit): 22 catalogs × 10
// fields is roughly 300 strings, half of them non-ASCII and none of them
// reviewable by eye — Arabic month abbreviations do not survive human
// proofreading. Transcribing them would be the largest single transcription
// risk in the port.
//
// **What this costs, stated plainly.** `catalogs_conformance_test.go` diffs the
// result against the same files it was generated from, so at generation time it
// cannot fail. Its value is not transcription checking but **drift detection**:
// it fails when the submodule is bumped and a catalog changed, and when someone
// hand-edits the generated file. That is a weaker guarantee than the error
// dictionary's — which was small enough to transcribe, so its diff really did
// check a human copy — and the difference is worth knowing before trusting it.
//
// **A second blind spot, from the same shape.** The tool and the test both read
// the YAML with `goccy/go-yaml` and the same struct tags, so a goccy defect —
// an escape, a BOM, a Unicode normalization — would land in the generated data
// and in the expectation alike, and the diff would agree with itself. Closing it
// needs a second parser: the data was checked against ruamel out of band, field
// by field, with zero differences, but nothing in the repo repeats that.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/goccy/go-yaml"
)

type catalogFile struct {
	Locale struct {
		Language           string   `yaml:"language"`
		LastUpdated        string   `yaml:"last_updated"`
		Month              string   `yaml:"month"`
		Months             string   `yaml:"months"`
		Year               string   `yaml:"year"`
		Years              string   `yaml:"years"`
		Present            string   `yaml:"present"`
		MonthAbbreviations []string `yaml:"month_abbreviations"`
		MonthNames         []string `yaml:"month_names"`
		Phrases            struct {
			DegreeWithArea string `yaml:"degree_with_area"`
		} `yaml:"phrases"`
	} `yaml:"locale"`
}

func main() {
	root := repoRoot()
	dir := filepath.Join(root,
		"third_party/rendercv/src/rendercv/schema/models/locale/other_locales")
	out := filepath.Join(root, "internal/schema/models/locale/catalogs_generated.go")

	paths, err := filepath.Glob(filepath.Join(dir, "*.yaml"))
	must(err)
	sort.Strings(paths)
	if len(paths) != 21 {
		fail("found %d override files, want 21", len(paths))
	}

	var body strings.Builder
	body.WriteString(header)
	for _, path := range paths {
		raw, err := os.ReadFile(path)
		must(err)
		var parsed catalogFile
		must(yaml.Unmarshal(raw, &parsed))

		c := parsed.Locale
		if len(c.MonthAbbreviations) != 12 || len(c.MonthNames) != 12 {
			fail("%s has %d abbreviations and %d names, want 12 of each",
				filepath.Base(path), len(c.MonthAbbreviations), len(c.MonthNames))
		}

		fmt.Fprintf(&body, "\t\t%q: {\n", c.Language)
		fmt.Fprintf(&body, "\t\t\tLanguage:       %q,\n", c.Language)
		fmt.Fprintf(&body, "\t\t\tLastUpdated:    %q,\n", c.LastUpdated)
		fmt.Fprintf(&body, "\t\t\tMonth:          %q,\n", c.Month)
		fmt.Fprintf(&body, "\t\t\tMonths:         %q,\n", c.Months)
		fmt.Fprintf(&body, "\t\t\tYear:           %q,\n", c.Year)
		fmt.Fprintf(&body, "\t\t\tYears:          %q,\n", c.Years)
		fmt.Fprintf(&body, "\t\t\tPresent:        %q,\n", c.Present)
		fmt.Fprintf(&body, "\t\t\tDegreeWithArea: %q,\n", c.Phrases.DegreeWithArea)
		writeList(&body, "MonthAbbreviations", c.MonthAbbreviations)
		writeList(&body, "MonthNames", c.MonthNames)
		body.WriteString("\t\t},\n")
	}
	body.WriteString("\t}\n}\n")

	must(os.WriteFile(out, []byte(body.String()), 0o644))
	fmt.Println("wrote", out)
}

func writeList(out *strings.Builder, field string, values []string) {
	fmt.Fprintf(out, "\t\t\t%s: []string{\n", field)
	for _, value := range values {
		fmt.Fprintf(out, "\t\t\t\t%q,\n", value)
	}
	out.WriteString("\t\t\t},\n")
}

const header = `// Code generated by tools/localeprobe. DO NOT EDIT.

package locale

// otherCatalogs is the twenty-one non-English locale catalogs, generated from
// third_party/rendercv/.../other_locales/*.yaml.
//
// Generated rather than transcribed: 210 strings, most of them non-ASCII and
// none proofreadable by eye. catalogs_conformance_test.go diffs this against the
// files it came from, which detects drift after a submodule bump — see
// tools/localeprobe for what that guarantee is and is not.
func otherCatalogs() map[string]Catalog {
	return map[string]Catalog{
`

func repoRoot() string {
	dir, err := os.Getwd()
	must(err)
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fail("no go.mod found")
		}
		dir = parent
	}
}

func must(err error) {
	if err != nil {
		fail("%v", err)
	}
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "localeprobe: "+format+"\n", args...)
	os.Exit(1)
}
