//go:build conformance

package design_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/nonamecat19/rendercv-go/internal/schema/models/design"
)

// The effective option tree against upstream's resolved model — iteration 6's
// T10, and the first thing that reads a theme's overrides for their *values*
// rather than for the `$defs` they produce.
//
// The fixture is upstream's own `m.design.<path>` for seven documents: four bare
// themes and three that override on top of one. It is generated by running the
// vendored Python, so what it pins is a measurement rather than my reading of
// the merge rule.
func TestEffectiveMatchesUpstream(t *testing.T) {
	path := filepath.Join("testdata", "effective.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	var fixture map[string]map[string]any
	if err := json.Unmarshal(raw, &fixture); err != nil {
		t.Fatalf("parsing %s: %v", path, err)
	}

	documents := map[string]map[string]any{
		"classic":              {},
		"sb2nov":               {},
		"engineeringresumes":   {},
		"moderncv":             {},
		"classic+margin":       {"page": map[string]any{"top_margin": "1cm"}},
		"sb2nov+one-font-size": {"typography": map[string]any{"font_size": map[string]any{"body": "9pt"}}},
		"classic+font-string":  {"typography": map[string]any{"font_family": "Roboto"}},
	}

	names := make([]string, 0, len(fixture))
	for name := range fixture {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		t.Run(name, func(t *testing.T) {
			theme, _, _ := strings.Cut(name, "+")
			values := design.Effective(theme, documents[name])

			for path, want := range fixture[name] {
				got := readPath(t, values, path)
				if !equal(got, want) {
					t.Errorf("%s = %#v, want %#v", path, got, want)
				}
			}
		})
	}
}

func readPath(t *testing.T, values map[string]any, path string) any {
	t.Helper()
	parts := strings.Split(path, ".")

	// `colors.body` is stored rendered, which is what upstream's `str()` gives.
	if parts[0] == "colors" {
		return design.EffectiveString(values, parts...)
	}
	if path == "sections.show_time_spans_in" {
		return design.EffectiveStrings(values, parts...)
	}
	if path == "links.underline" || path == "entries.short_second_row" {
		return design.EffectiveBool(values, parts...)
	}
	return design.EffectiveString(values, parts...)
}

func equal(got, want any) bool {
	list, isList := got.([]string)
	if !isList {
		if wantBool, ok := want.(bool); ok {
			gotBool, _ := got.(bool)
			return gotBool == wantBool
		}
		wantText, _ := want.(string)
		gotText, _ := got.(string)
		return gotText == wantText
	}

	wantList, ok := want.([]any)
	if !ok || len(wantList) != len(list) {
		return false
	}
	for i := range list {
		text, _ := wantList[i].(string)
		if list[i] != text {
			return false
		}
	}
	return true
}
