// Code generated by tools/designprobe. DO NOT EDIT.

package design

// themeOverrides is the eight YAML-defined themes, each the `design` mapping of
// other_themes/<stem>.yaml.
//
// A variant is ClassicTheme with these defaults replaced and its `theme` literal
// pinned to the stem (spec 006 §1 behavior 1) — so what is stored is the
// override, not a ninth tree.
//
// **Which keys a theme names is contractual beyond its own defaults**: it also
// decides the $defs collision numbering, because a theme that omits a block
// points back at the base's __1 (plan §4).
func themeOverrides() map[string]map[string]any {
	return map[string]map[string]any{
		"ember": {
			"colors": map[string]any{
				"body":           "rgb(35, 31, 32)",
				"connections":    "rgb(100, 75, 68)",
				"footer":         "rgb(140, 125, 118)",
				"headline":       "rgb(90, 60, 55)",
				"links":          "rgb(155, 35, 25)",
				"name":           "rgb(155, 35, 25)",
				"section_titles": "rgb(155, 35, 25)",
				"top_note":       "rgb(140, 125, 118)",
			},
			"entries": map[string]any{
				"highlights": map[string]any{
					"bullet":                        "◆",
					"nested_bullet":                 "◦",
					"space_above":                   "0.05cm",
					"space_between_bullet_and_text": "0.5em",
					"space_between_items":           "0.04cm",
					"space_left":                    "0.15cm",
				},
				"short_second_row":      false,
				"side_space":            "0.1cm",
				"space_between_columns": "0.15cm",
				"summary": map[string]any{
					"space_above": "0.05cm",
				},
			},
			"header": map[string]any{
				"alignment": "center",
				"connections": map[string]any{
					"separator":                 "·",
					"show_icons":                false,
					"space_between_connections": "0.5cm",
				},
				"space_below_connections": "0.6cm",
				"space_below_headline":    "0.4cm",
				"space_below_name":        "0.5cm",
			},
			"links": map[string]any{
				"show_external_link_icon": false,
				"underline":               true,
			},
			"page": map[string]any{
				"bottom_margin": "0.6in",
				"left_margin":   "0.6in",
				"right_margin":  "0.6in",
				"top_margin":    "0.6in",
			},
			"section_titles": map[string]any{
				"line_thickness": "0.5pt",
				"space_above":    "0.55cm",
				"space_below":    "0.25cm",
				"type":           "centered_without_line",
			},
			"sections": map[string]any{
				"show_time_spans_in":               []string{},
				"space_between_regular_entries":    "1.1em",
				"space_between_text_based_entries": "0.3em",
			},
			"templates": map[string]any{
				"education_entry": map[string]any{
					"date_and_location_column": "DATE",
					"degree_column":            nil,
					"main_column":              "**INSTITUTION** -- LOCATION\n*DEGREE_WITH_AREA*\nSUMMARY\nHIGHLIGHTS",
				},
				"experience_entry": map[string]any{
					"date_and_location_column": "DATE",
					"main_column":              "**COMPANY** -- LOCATION\n*POSITION*\nSUMMARY\nHIGHLIGHTS",
				},
				"normal_entry": map[string]any{
					"date_and_location_column": "DATE",
					"main_column":              "**NAME** -- LOCATION\nSUMMARY\nHIGHLIGHTS",
				},
			},
			"theme": "ember",
			"typography": map[string]any{
				"alignment": "justified-with-no-hyphenation",
				"bold": map[string]any{
					"connections":    false,
					"headline":       false,
					"name":           true,
					"section_titles": false,
				},
				"font_family": map[string]any{
					"body":           "Ubuntu",
					"connections":    "Ubuntu",
					"headline":       "Gentium Book Plus",
					"name":           "Gentium Book Plus",
					"section_titles": "Ubuntu",
				},
				"font_size": map[string]any{
					"body":           "10pt",
					"connections":    "9pt",
					"headline":       "10.5pt",
					"name":           "30pt",
					"section_titles": "1.25em",
				},
				"line_spacing": "0.6em",
				"small_caps": map[string]any{
					"connections":    false,
					"headline":       true,
					"name":           false,
					"section_titles": true,
				},
			},
		},
		"engineeringclassic": {
			"entries": map[string]any{
				"highlights": map[string]any{
					"space_above":         "0.12cm",
					"space_between_items": "0.12cm",
					"space_left":          "0cm",
				},
				"short_second_row": false,
				"summary": map[string]any{
					"space_above": "0.12cm",
				},
			},
			"header": map[string]any{
				"alignment": "left",
			},
			"links": map[string]any{
				"show_external_link_icon": false,
			},
			"section_titles": map[string]any{
				"type": "with_full_line",
			},
			"sections": map[string]any{
				"show_time_spans_in": []string{},
			},
			"templates": map[string]any{
				"education_entry": map[string]any{
					"date_and_location_column": "DATE",
					"degree_column":            nil,
					"main_column":              "**INSTITUTION**, DEGREE_WITH_AREA -- LOCATION\nSUMMARY\nHIGHLIGHTS",
				},
				"experience_entry": map[string]any{
					"date_and_location_column": "DATE",
					"main_column":              "**POSITION**, COMPANY -- LOCATION\nSUMMARY\nHIGHLIGHTS",
				},
				"normal_entry": map[string]any{
					"date_and_location_column": "DATE",
					"main_column":              "**NAME** -- **LOCATION**\nSUMMARY\nHIGHLIGHTS",
				},
			},
			"theme": "engineeringclassic",
			"typography": map[string]any{
				"bold": map[string]any{
					"name":           false,
					"section_titles": false,
				},
				"font_family": map[string]any{
					"body":           "Raleway",
					"connections":    "Raleway",
					"headline":       "Raleway",
					"name":           "Raleway",
					"section_titles": "Raleway",
				},
			},
		},
		"engineeringresumes": {
			"colors": map[string]any{
				"connections":    "rgb(0,0,0)",
				"headline":       "rgb(0,0,0)",
				"links":          "rgb(0,0,0)",
				"name":           "rgb(0,0,0)",
				"section_titles": "rgb(0,0,0)",
			},
			"entries": map[string]any{
				"highlights": map[string]any{
					"bullet":                        "●",
					"nested_bullet":                 "●",
					"space_above":                   "0.08cm",
					"space_between_bullet_and_text": "0.3em",
					"space_between_items":           "0.08cm",
					"space_left":                    "0cm",
				},
				"short_second_row": false,
				"side_space":       "0cm",
				"summary": map[string]any{
					"space_above": "0.08cm",
				},
			},
			"header": map[string]any{
				"connections": map[string]any{
					"display_urls_instead_of_usernames": true,
					"separator":                         "|",
					"show_icons":                        false,
				},
			},
			"links": map[string]any{
				"show_external_link_icon": false,
				"underline":               true,
			},
			"page": map[string]any{
				"show_footer": false,
			},
			"section_titles": map[string]any{
				"space_above": "0.5cm",
				"space_below": "0.3cm",
				"type":        "with_full_line",
			},
			"sections": map[string]any{
				"show_time_spans_in":               []string{},
				"space_between_regular_entries":    "0.42cm",
				"space_between_text_based_entries": "0.15cm",
			},
			"templates": map[string]any{
				"education_entry": map[string]any{
					"date_and_location_column": "DATE",
					"degree_column":            nil,
					"main_column":              "**INSTITUTION**, DEGREE_WITH_AREA -- LOCATION\nSUMMARY\nHIGHLIGHTS",
				},
				"experience_entry": map[string]any{
					"date_and_location_column": "DATE",
					"main_column":              "**POSITION**, COMPANY -- LOCATION\nSUMMARY\nHIGHLIGHTS",
				},
				"normal_entry": map[string]any{
					"date_and_location_column": "DATE",
					"main_column":              "**NAME** -- **LOCATION**\nSUMMARY\nHIGHLIGHTS",
				},
			},
			"theme": "engineeringresumes",
			"typography": map[string]any{
				"bold": map[string]any{
					"name": false,
				},
				"font_family": map[string]any{
					"body":           "XCharter",
					"connections":    "XCharter",
					"headline":       "XCharter",
					"name":           "XCharter",
					"section_titles": "XCharter",
				},
				"font_size": map[string]any{
					"name":           "25pt",
					"section_titles": "1.2em",
				},
			},
		},
		"harvard": {
			"colors": map[string]any{
				"connections":    "rgb(0,0,0)",
				"headline":       "rgb(0,0,0)",
				"links":          "rgb(0,0,0)",
				"name":           "rgb(0,0,0)",
				"section_titles": "rgb(0,0,0)",
			},
			"entries": map[string]any{
				"short_second_row": false,
			},
			"header": map[string]any{
				"connections": map[string]any{
					"separator":                 "•",
					"show_icons":                false,
					"space_between_connections": "0.4cm",
				},
				"space_below_connections": "0.5cm",
				"space_below_headline":    "0.5cm",
				"space_below_name":        "0.5cm",
			},
			"page": map[string]any{
				"bottom_margin": "0.5in",
				"left_margin":   "0.5in",
				"right_margin":  "0.5in",
				"show_top_note": false,
				"top_margin":    "0.5in",
			},
			"section_titles": map[string]any{
				"space_below": "0.2cm",
				"type":        "centered_with_centered_partial_line",
			},
			"sections": map[string]any{
				"show_time_spans_in":            []string{},
				"space_between_regular_entries": "1em",
			},
			"templates": map[string]any{
				"education_entry": map[string]any{
					"date_and_location_column": "DATE",
					"main_column":              "**INSTITUTION**, DEGREE_WITH_AREA -- LOCATION\nSUMMARY\nHIGHLIGHTS",
				},
				"experience_entry": map[string]any{
					"date_and_location_column": "DATE",
					"main_column":              "**COMPANY**, POSITION -- LOCATION\nSUMMARY\nHIGHLIGHTS",
				},
				"normal_entry": map[string]any{
					"date_and_location_column": "DATE",
					"main_column":              "**NAME** -- **LOCATION**\nSUMMARY\nHIGHLIGHTS",
				},
				"time_span": "",
			},
			"theme": "harvard",
			"typography": map[string]any{
				"font_family": map[string]any{
					"body":           "XCharter",
					"connections":    "XCharter",
					"headline":       "XCharter",
					"name":           "XCharter",
					"section_titles": "XCharter",
				},
				"font_size": map[string]any{
					"connections":    "9pt",
					"name":           "25pt",
					"section_titles": "1.3em",
				},
			},
		},
		"ink": {
			"colors": map[string]any{
				"connections":    "rgb(70, 50, 110)",
				"footer":         "rgb(120, 100, 140)",
				"headline":       "rgb(42, 24, 82)",
				"links":          "rgb(42, 24, 82)",
				"name":           "rgb(42, 24, 82)",
				"section_titles": "rgb(42, 24, 82)",
				"top_note":       "rgb(120, 100, 140)",
			},
			"entries": map[string]any{
				"highlights": map[string]any{
					"bullet":                        "•",
					"nested_bullet":                 "•",
					"space_above":                   "0.06cm",
					"space_between_bullet_and_text": "0.4em",
					"space_between_items":           "0.06cm",
					"space_left":                    "0cm",
				},
				"short_second_row":      false,
				"side_space":            "0cm",
				"space_between_columns": "0.2cm",
				"summary": map[string]any{
					"space_above": "0.06cm",
				},
			},
			"header": map[string]any{
				"alignment": "left",
				"connections": map[string]any{
					"display_urls_instead_of_usernames": true,
					"separator":                         "|",
					"show_icons":                        false,
					"space_between_connections":         "0.4cm",
				},
				"space_below_connections": "0.5cm",
				"space_below_headline":    "0.4cm",
				"space_below_name":        "0.5cm",
			},
			"links": map[string]any{
				"show_external_link_icon": false,
				"underline":               true,
			},
			"page": map[string]any{
				"bottom_margin": "0.6in",
				"left_margin":   "0.6in",
				"right_margin":  "0.6in",
				"top_margin":    "0.6in",
			},
			"section_titles": map[string]any{
				"space_above": "0.5cm",
				"space_below": "0.2cm",
				"type":        "without_line",
			},
			"sections": map[string]any{
				"show_time_spans_in":               []string{},
				"space_between_regular_entries":    "1em",
				"space_between_text_based_entries": "0.2em",
			},
			"templates": map[string]any{
				"education_entry": map[string]any{
					"date_and_location_column": "DATE",
					"degree_column":            nil,
					"main_column":              "**INSTITUTION** -- LOCATION\n*DEGREE_WITH_AREA*\nSUMMARY\nHIGHLIGHTS",
				},
				"experience_entry": map[string]any{
					"date_and_location_column": "DATE",
					"main_column":              "**COMPANY** -- LOCATION\n*POSITION*\nSUMMARY\nHIGHLIGHTS",
				},
				"normal_entry": map[string]any{
					"date_and_location_column": "DATE",
					"main_column":              "**NAME** -- **LOCATION**\nSUMMARY\nHIGHLIGHTS",
				},
			},
			"theme": "ink",
			"typography": map[string]any{
				"alignment": "justified",
				"bold": map[string]any{
					"connections":    false,
					"headline":       false,
					"name":           true,
					"section_titles": true,
				},
				"font_family": map[string]any{
					"body":           "EB Garamond",
					"connections":    "EB Garamond",
					"headline":       "EB Garamond",
					"name":           "EB Garamond",
					"section_titles": "EB Garamond",
				},
				"font_size": map[string]any{
					"body":           "10pt",
					"connections":    "10pt",
					"headline":       "11pt",
					"name":           "32pt",
					"section_titles": "1.4em",
				},
				"line_spacing": "0.55em",
				"small_caps": map[string]any{
					"headline":       false,
					"name":           false,
					"section_titles": true,
				},
			},
		},
		"moderncv": {
			"entries": map[string]any{
				"highlights": map[string]any{
					"space_above":                   "0.15cm",
					"space_between_bullet_and_text": "0.3em",
					"space_between_items":           "0.1cm",
					"space_left":                    "0cm",
				},
				"short_second_row":      false,
				"side_space":            "0cm",
				"space_between_columns": "0.3cm",
				"summary": map[string]any{
					"space_above": "0.1cm",
				},
			},
			"header": map[string]any{
				"alignment":         "left",
				"photo_space_left":  "0cm",
				"photo_space_right": "0.3cm",
				"photo_width":       "4.15cm",
			},
			"links": map[string]any{
				"show_external_link_icon": false,
				"underline":               true,
			},
			"section_titles": map[string]any{
				"line_thickness": "0.15cm",
				"space_above":    "0.55cm",
				"space_below":    "0.3cm",
				"type":           "moderncv",
			},
			"sections": map[string]any{
				"show_time_spans_in": []string{},
			},
			"templates": map[string]any{
				"education_entry": map[string]any{
					"date_and_location_column": "DATE",
					"degree_column":            nil,
					"main_column":              "**INSTITUTION**, DEGREE_WITH_AREA -- LOCATION\nSUMMARY\nHIGHLIGHTS",
				},
				"experience_entry": map[string]any{
					"date_and_location_column": "DATE",
					"main_column":              "**POSITION**, COMPANY -- LOCATION\nSUMMARY\nHIGHLIGHTS",
				},
				"normal_entry": map[string]any{
					"date_and_location_column": "DATE",
					"main_column":              "**NAME** -- **LOCATION**\nSUMMARY\nHIGHLIGHTS",
				},
			},
			"theme": "moderncv",
			"typography": map[string]any{
				"bold": map[string]any{
					"name":           false,
					"section_titles": false,
				},
				"font_family": map[string]any{
					"body":           "Fontin",
					"connections":    "Fontin",
					"headline":       "Fontin",
					"name":           "Fontin",
					"section_titles": "Fontin",
				},
				"font_size": map[string]any{
					"name":           "25pt",
					"section_titles": "1.4em",
				},
				"line_spacing": "0.6em",
			},
		},
		"opal": {
			"colors": map[string]any{
				"connections":    "rgb(0, 80, 72)",
				"footer":         "rgb(100, 140, 135)",
				"headline":       "rgb(0, 80, 72)",
				"links":          "rgb(0, 100, 90)",
				"name":           "rgb(0, 100, 90)",
				"section_titles": "rgb(0, 100, 90)",
				"top_note":       "rgb(100, 140, 135)",
			},
			"entries": map[string]any{
				"highlights": map[string]any{
					"bullet":                        "◦",
					"nested_bullet":                 "◦",
					"space_above":                   "0.04cm",
					"space_between_bullet_and_text": "0.5em",
					"space_between_items":           "0.04cm",
					"space_left":                    "0.15cm",
				},
				"short_second_row":      true,
				"side_space":            "0.15cm",
				"space_between_columns": "0.1cm",
				"summary": map[string]any{
					"space_above": "0.04cm",
				},
			},
			"header": map[string]any{
				"alignment": "center",
				"connections": map[string]any{
					"separator":                 "•",
					"show_icons":                true,
					"space_between_connections": "0.5cm",
				},
				"space_below_connections": "0.6cm",
				"space_below_headline":    "0.3cm",
				"space_below_name":        "0.3cm",
			},
			"links": map[string]any{
				"show_external_link_icon": false,
				"underline":               false,
			},
			"page": map[string]any{
				"bottom_margin": "0.65in",
				"left_margin":   "0.65in",
				"right_margin":  "0.65in",
				"show_footer":   false,
				"show_top_note": false,
				"top_margin":    "0.65in",
			},
			"section_titles": map[string]any{
				"line_thickness": "0.4pt",
				"space_above":    "0.55cm",
				"space_below":    "0.25cm",
				"type":           "centered_without_line",
			},
			"sections": map[string]any{
				"show_time_spans_in":               []string{},
				"space_between_regular_entries":    "1.1em",
				"space_between_text_based_entries": "0.3em",
			},
			"templates": map[string]any{
				"education_entry": map[string]any{
					"date_and_location_column": "DATE",
					"degree_column":            nil,
					"main_column":              "**INSTITUTION** -- LOCATION\nDEGREE_WITH_AREA\nSUMMARY\nHIGHLIGHTS",
				},
				"experience_entry": map[string]any{
					"date_and_location_column": "DATE",
					"main_column":              "**COMPANY**, *POSITION* -- LOCATION\nSUMMARY\nHIGHLIGHTS",
				},
				"normal_entry": map[string]any{
					"date_and_location_column": "DATE",
					"main_column":              "**NAME** -- LOCATION\nSUMMARY\nHIGHLIGHTS",
				},
			},
			"theme": "opal",
			"typography": map[string]any{
				"alignment": "left",
				"bold": map[string]any{
					"connections":    false,
					"headline":       false,
					"name":           true,
					"section_titles": false,
				},
				"font_family": map[string]any{
					"body":           "Lato",
					"connections":    "Lato",
					"headline":       "Lato",
					"name":           "Lato",
					"section_titles": "Lato",
				},
				"font_size": map[string]any{
					"body":           "10pt",
					"connections":    "9pt",
					"headline":       "10pt",
					"name":           "26pt",
					"section_titles": "1.2em",
				},
				"line_spacing": "0.6em",
				"small_caps": map[string]any{
					"connections":    false,
					"headline":       true,
					"name":           false,
					"section_titles": true,
				},
			},
		},
		"sb2nov": {
			"colors": map[string]any{
				"connections":    "rgb(0,0,0)",
				"headline":       "rgb(0,0,0)",
				"links":          "rgb(0,0,0)",
				"name":           "rgb(0,0,0)",
				"section_titles": "rgb(0,0,0)",
			},
			"entries": map[string]any{
				"highlights": map[string]any{
					"bullet":        "◦",
					"nested_bullet": "◦",
				},
				"short_second_row": false,
			},
			"header": map[string]any{
				"connections": map[string]any{
					"display_urls_instead_of_usernames": true,
					"hyperlink":                         true,
					"separator":                         "•",
					"show_icons":                        false,
				},
			},
			"links": map[string]any{
				"show_external_link_icon": false,
				"underline":               true,
			},
			"section_titles": map[string]any{
				"type": "with_full_line",
			},
			"sections": map[string]any{
				"show_time_spans_in": []string{},
			},
			"templates": map[string]any{
				"education_entry": map[string]any{
					"date_and_location_column": "*LOCATION*\n*DATE*",
					"degree_column":            nil,
					"main_column":              "**INSTITUTION**\n*DEGREE* *in* *AREA*\nSUMMARY\nHIGHLIGHTS",
				},
				"experience_entry": map[string]any{
					"date_and_location_column": "*LOCATION*\n*DATE*",
					"main_column":              "**POSITION**\n*COMPANY*\nSUMMARY\nHIGHLIGHTS",
				},
				"normal_entry": map[string]any{
					"date_and_location_column": "*LOCATION*\n*DATE*",
				},
			},
			"theme": "sb2nov",
			"typography": map[string]any{
				"font_family": map[string]any{
					"body":           "New Computer Modern",
					"connections":    "New Computer Modern",
					"headline":       "New Computer Modern",
					"name":           "New Computer Modern",
					"section_titles": "New Computer Modern",
				},
			},
		},
	}
}
