// Code generated by tools/designprobe. DO NOT EDIT.

package design

// baseTree is ClassicTheme's option tree: twenty-two models, every field, every
// default and every description, introspected out of the vendored Python.
//
// Generated rather than transcribed. The descriptions run to hundreds of bytes
// and list template placeholders line by line; a typo in one is invisible to
// review and reports as one of 161 byte failures in the $defs differential. See
// tools/designprobe for what that guarantee is and is not.
func baseTree() Tree {
	return Tree{
		Root: "ClassicTheme",
		Models: map[string]Model{
			"Page": {Name: "Page", Fields: []Field{
				{Name: "size", Kind: KindLiteral, Ref: "PageSize", Members: PageSizes, Default: "us-letter", Description: "The page size. Use 'a4' (international standard) or 'us-letter' (US standard). The default value is `us-letter`."},
				{Name: "top_margin", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0.7in", Description: "It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0.7in`."},
				{Name: "bottom_margin", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0.7in", Description: "It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0.7in`."},
				{Name: "left_margin", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0.7in", Description: "It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0.7in`."},
				{Name: "right_margin", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0.7in", Description: "It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0.7in`."},
				{Name: "show_footer", Kind: KindBool, Default: true, Description: "Show the footer at the bottom of pages. The default value is `true`."},
				{Name: "show_top_note", Kind: KindBool, Default: true, Description: "Show the top note at the top of the first page. The default value is `true`."},
			}},
			"Colors": {Name: "Colors", Fields: []Field{
				{Name: "body", Kind: KindColor, Default: "rgb(0, 0, 0)", Description: "The color can be specified either with their name (https://www.w3.org/TR/SVG11/types.html#ColorKeywords), hexadecimal value, RGB value, or HSL value. The default value is `rgb(0, 0, 0)`.", Examples: []any{"Black", "7fffd4", "rgb(0,79,144)", "hsl(270, 60%, 70%)"}},
				{Name: "name", Kind: KindColor, Default: "rgb(0, 79, 144)", Description: "The color can be specified either with their name (https://www.w3.org/TR/SVG11/types.html#ColorKeywords), hexadecimal value, RGB value, or HSL value. The default value is `rgb(0, 79, 144)`.", Examples: []any{"Black", "7fffd4", "rgb(0,79,144)", "hsl(270, 60%, 70%)"}},
				{Name: "headline", Kind: KindColor, Default: "rgb(0, 79, 144)", Description: "The color can be specified either with their name (https://www.w3.org/TR/SVG11/types.html#ColorKeywords), hexadecimal value, RGB value, or HSL value. The default value is `rgb(0, 79, 144)`.", Examples: []any{"Black", "7fffd4", "rgb(0,79,144)", "hsl(270, 60%, 70%)"}},
				{Name: "connections", Kind: KindColor, Default: "rgb(0, 79, 144)", Description: "The color can be specified either with their name (https://www.w3.org/TR/SVG11/types.html#ColorKeywords), hexadecimal value, RGB value, or HSL value. The default value is `rgb(0, 79, 144)`.", Examples: []any{"Black", "7fffd4", "rgb(0,79,144)", "hsl(270, 60%, 70%)"}},
				{Name: "section_titles", Kind: KindColor, Default: "rgb(0, 79, 144)", Description: "The color can be specified either with their name (https://www.w3.org/TR/SVG11/types.html#ColorKeywords), hexadecimal value, RGB value, or HSL value. The default value is `rgb(0, 79, 144)`.", Examples: []any{"Black", "7fffd4", "rgb(0,79,144)", "hsl(270, 60%, 70%)"}},
				{Name: "links", Kind: KindColor, Default: "rgb(0, 79, 144)", Description: "The color can be specified either with their name (https://www.w3.org/TR/SVG11/types.html#ColorKeywords), hexadecimal value, RGB value, or HSL value. The default value is `rgb(0, 79, 144)`.", Examples: []any{"Black", "7fffd4", "rgb(0,79,144)", "hsl(270, 60%, 70%)"}},
				{Name: "footer", Kind: KindColor, Default: "rgb(128, 128, 128)", Description: "The color can be specified either with their name (https://www.w3.org/TR/SVG11/types.html#ColorKeywords), hexadecimal value, RGB value, or HSL value. The default value is `rgb(128, 128, 128)`.", Examples: []any{"Black", "7fffd4", "rgb(0,79,144)", "hsl(270, 60%, 70%)"}},
				{Name: "top_note", Kind: KindColor, Default: "rgb(128, 128, 128)", Description: "The color can be specified either with their name (https://www.w3.org/TR/SVG11/types.html#ColorKeywords), hexadecimal value, RGB value, or HSL value. The default value is `rgb(128, 128, 128)`.", Examples: []any{"Black", "7fffd4", "rgb(0,79,144)", "hsl(270, 60%, 70%)"}},
			}},
			"FontSize": {Name: "FontSize", Fields: []Field{
				{Name: "body", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "10pt", Description: "The font size for body text. The default value is `10pt`."},
				{Name: "name", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "30pt", Description: "The font size for the name. The default value is `30pt`."},
				{Name: "headline", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "10pt", Description: "The font size for the headline. The default value is `10pt`."},
				{Name: "connections", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "10pt", Description: "The font size for connections. The default value is `10pt`."},
				{Name: "section_titles", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "1.4em", Description: "The font size for section titles. The default value is `1.4em`."},
			}},
			"SmallCaps": {Name: "SmallCaps", Fields: []Field{
				{Name: "name", Kind: KindBool, Default: false, Description: "Whether to use small caps for the name. The default value is `false`."},
				{Name: "headline", Kind: KindBool, Default: false, Description: "Whether to use small caps for the headline. The default value is `false`."},
				{Name: "connections", Kind: KindBool, Default: false, Description: "Whether to use small caps for connections. The default value is `false`."},
				{Name: "section_titles", Kind: KindBool, Default: false, Description: "Whether to use small caps for section titles. The default value is `false`."},
			}},
			"Bold": {Name: "Bold", Fields: []Field{
				{Name: "name", Kind: KindBool, Default: true, Description: "Whether to make the name bold. The default value is `true`."},
				{Name: "headline", Kind: KindBool, Default: false, Description: "Whether to make the headline bold. The default value is `false`."},
				{Name: "connections", Kind: KindBool, Default: false, Description: "Whether to make connections bold. The default value is `false`."},
				{Name: "section_titles", Kind: KindBool, Default: true, Description: "Whether to make section titles bold. The default value is `true`."},
			}},
			"Typography": {Name: "Typography", Fields: []Field{
				{Name: "line_spacing", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0.6em", Description: "Space between lines of text. Larger values create more vertical space. The default value is `0.6em`."},
				{Name: "alignment", Kind: KindLiteral, Members: BodyAlignments, Default: "justified", Description: "Text alignment. Options: 'left', 'justified' (spreads text across full width), 'justified-with-no-hyphenation' (justified without word breaks). The default value is `justified`."},
				{Name: "date_and_location_column_alignment", Kind: KindLiteral, Ref: "Alignment", Members: Alignments, Default: "right", Description: "Alignment for dates and locations in entries. Options: 'left', 'center', 'right'. The default value is `right`."},
				{Name: "font_family", Kind: KindFontFamily, Description: "The font family. You can provide a single font name as a string (applies to all elements), or a dictionary with keys 'body', 'name', 'headline', 'connections', and 'section_titles' to customize each element. Any system font can be used."},
				{Name: "font_size", Kind: KindNested, Nested: "FontSize", Description: "Font sizes for different elements."},
				{Name: "small_caps", Kind: KindNested, Nested: "SmallCaps", Description: "Small caps styling for different elements."},
				{Name: "bold", Kind: KindNested, Nested: "Bold", Description: "Bold styling for different elements."},
			}},
			"Links": {Name: "Links", Fields: []Field{
				{Name: "underline", Kind: KindBool, Default: false, Description: "Underline hyperlinks. The default value is `false`."},
				{Name: "show_external_link_icon", Kind: KindBool, Default: false, Description: "Show an external link icon next to URLs. The default value is `false`."},
			}},
			"Connections": {Name: "Connections", Fields: []Field{
				{Name: "phone_number_format", Kind: KindLiteral, Ref: "PhoneNumberFormatType", Members: PhoneNumberFormats, Default: "national", Description: "Phone number format. The default value is `national`."},
				{Name: "hyperlink", Kind: KindBool, Default: true, Description: "Make contact information clickable in the PDF. The default value is `true`."},
				{Name: "show_icons", Kind: KindBool, Default: true, Description: "Show icons next to contact information. The default value is `true`."},
				{Name: "display_urls_instead_of_usernames", Kind: KindBool, Default: false, Description: "Display full URLs instead of labels. The default value is `false`."},
				{Name: "separator", Kind: KindString, Default: "", Description: "Character(s) to separate contact items (e.g., '|' or '•'). Leave empty for no separator. The default value is `''`."},
				{Name: "space_between_connections", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0.5cm", Description: "Horizontal space between contact items. It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0.5cm`."},
			}},
			"Header": {Name: "Header", Fields: []Field{
				{Name: "alignment", Kind: KindLiteral, Ref: "Alignment", Members: Alignments, Default: "center", Description: "Header alignment. Options: 'left', 'center', 'right'. The default value is `center`."},
				{Name: "photo_width", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "3.5cm", Description: "Photo width. It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `3.5cm`."},
				{Name: "photo_position", Kind: KindLiteral, Members: PhotoPositions, Default: "left", Description: "Photo position (left or right). The default value is `left`."},
				{Name: "photo_space_left", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0.4cm", Description: "Space to the left of the photo. It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0.4cm`."},
				{Name: "photo_space_right", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0.4cm", Description: "Space to the right of the photo. It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0.4cm`."},
				{Name: "space_below_name", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0.7cm", Description: "Space below your name. It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0.7cm`."},
				{Name: "space_below_headline", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0.7cm", Description: "Space below the headline. It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0.7cm`."},
				{Name: "space_below_connections", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0.7cm", Description: "Space below contact information. It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0.7cm`."},
				{Name: "connections", Kind: KindNested, Nested: "Connections", Description: "Contact information settings."},
			}},
			"SectionTitles": {Name: "SectionTitles", Fields: []Field{
				{Name: "type", Kind: KindLiteral, Ref: "SectionTitleType", Members: SectionTitleTypes, Default: "with_partial_line", Description: "Section title visual style. Use 'with_partial_line' for a line next to the title, 'with_full_line' for a line across the page, 'without_line' for no line, 'moderncv' for the ModernCV style, 'centered_without_line' for a centered title with no line, 'centered_with_partial_line' for a centered title with baseline partial lines on both sides, 'centered_with_centered_partial_line' for a centered title with middle-aligned lines on both sides, or 'centered_with_full_line' for a full-width line underneath. The default value is `with_partial_line`."},
				{Name: "line_thickness", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0.5pt", Description: "It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0.5pt`."},
				{Name: "space_above", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0.5cm", Description: "It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0.5cm`."},
				{Name: "space_below", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0.3cm", Description: "It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0.3cm`."},
			}},
			"Sections": {Name: "Sections", Fields: []Field{
				{Name: "allow_page_break", Kind: KindBool, Default: true, Description: "Allow page breaks within sections. If false, sections that don't fit will start on a new page. The default value is `true`."},
				{Name: "space_between_regular_entries", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "1.2em", Description: "Vertical space between entries. It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `1.2em`."},
				{Name: "space_between_text_based_entries", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0.3em", Description: "Vertical space between text-based entries. It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0.3em`."},
				{Name: "show_time_spans_in", Kind: KindStringList, Default: []string{"experience"}, Description: "Section titles where time spans (e.g., '2 years 3 months') should be displayed. The default value is `['experience']`.", Examples: []any{[]any{"Experience"}, []any{"Experience", "Education"}}},
			}},
			"Summary": {Name: "Summary", Fields: []Field{
				{Name: "space_above", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0cm", Description: "Space above summary text. It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0cm`."},
				{Name: "space_left", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0cm", Description: "Left margin for summary text. It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0cm`."},
			}},
			"Highlights": {Name: "Highlights", Fields: []Field{
				{Name: "bullet", Kind: KindLiteral, Ref: "Bullet", Members: Bullets, Default: "•", Description: "Bullet character for highlights. The default value is `•`."},
				{Name: "nested_bullet", Kind: KindLiteral, Ref: "Bullet", Members: Bullets, Default: "•", Description: "Bullet character for nested highlights. The default value is `•`."},
				{Name: "space_left", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0.15cm", Description: "Left indentation. It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0.15cm`."},
				{Name: "space_above", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0cm", Description: "Space above highlights. It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0cm`."},
				{Name: "space_between_items", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0cm", Description: "Space between highlight items. It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0cm`."},
				{Name: "space_between_bullet_and_text", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0.5em", Description: "Space between bullet and text. It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0.5em`."},
			}},
			"Entries": {Name: "Entries", Fields: []Field{
				{Name: "date_and_location_width", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "4.15cm", Description: "Width of the date/location column. It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `4.15cm`."},
				{Name: "side_space", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0.2cm", Description: "Left and right margins. It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0.2cm`."},
				{Name: "space_between_columns", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "0.1cm", Description: "Space between main content and date/location columns. It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `0.1cm`."},
				{Name: "allow_page_break", Kind: KindBool, Default: false, Description: "Allow page breaks within entries. If false, entries that don't fit will move to a new page. The default value is `false`."},
				{Name: "short_second_row", Kind: KindBool, Default: true, Description: "Shorten the second row to align with the date/location column. The default value is `true`."},
				{Name: "degree_width", Kind: KindTypstDimension, Ref: "TypstDimension", Default: "1cm", Description: "Width of the degree column. It can be specified with units (cm, in, pt, mm, em). For example, `0.1cm`. The default value is `1cm`."},
				{Name: "summary", Kind: KindNested, Nested: "Summary", Description: "Summary text settings."},
				{Name: "highlights", Kind: KindNested, Nested: "Highlights", Description: "Highlights settings."},
			}},
			"OneLineEntry": {Name: "OneLineEntry", Fields: []Field{
				{Name: "main_column", Kind: KindString, Default: "**LABEL:** DETAILS", Description: "Template for one-line entries. Available placeholders:\n- `LABEL`: The label text (e.g., \"Languages\", \"Citizenship\")\n- `DETAILS`: The details text (e.g., \"English (native), Spanish (fluent)\")\n\nYou can also add arbitrary keys to entries and use them as UPPERCASE placeholders.\n\nThe default value is `**LABEL:** DETAILS`."},
			}},
			"EducationEntry": {Name: "EducationEntry", Fields: []Field{
				{Name: "main_column", Kind: KindString, Default: "**INSTITUTION**, AREA\nSUMMARY\nHIGHLIGHTS", Description: "Template for education entry main column. Available placeholders:\n- `INSTITUTION`: Institution name\n- `AREA`: Field of study/major\n- `DEGREE`: Degree type (e.g., BS, PhD)\n- `DEGREE_WITH_AREA`: Locale-aware phrase combining degree and area (e.g., 'BS in Computer Science')\n- `SUMMARY`: Summary text\n- `HIGHLIGHTS`: Bullet points list\n- `LOCATION`: Location text\n- `DATE`: Formatted date or date range\n\nYou can also add arbitrary keys to entries and use them as UPPERCASE placeholders.\n\nThe default value is `**INSTITUTION**, AREA\\nSUMMARY\\nHIGHLIGHTS`."},
				{Name: "degree_column", Kind: KindOptionalString, Default: "**DEGREE**", Description: "Optional degree column template. If provided, displays degree in separate column. If `null`, no degree column is shown. Available placeholders:\n- `INSTITUTION`: Institution name\n- `AREA`: Field of study/major\n- `DEGREE`: Degree type (e.g., BS, PhD)\n- `SUMMARY`: Summary text\n- `HIGHLIGHTS`: Bullet points list\n- `LOCATION`: Location text\n- `DATE`: Formatted date or date range\n\nYou can also add arbitrary keys to entries and use them as UPPERCASE placeholders.\n\nThe default value is `**DEGREE**`."},
				{Name: "date_and_location_column", Kind: KindString, Default: "LOCATION\nDATE", Description: "Template for education entry date/location column. Available placeholders:\n- `INSTITUTION`: Institution name\n- `AREA`: Field of study/major\n- `DEGREE`: Degree type (e.g., BS, PhD)\n- `SUMMARY`: Summary text\n- `HIGHLIGHTS`: Bullet points list\n- `LOCATION`: Location text\n- `DATE`: Formatted date or date range\n\nYou can also add arbitrary keys to entries and use them as UPPERCASE placeholders.\n\nThe default value is `LOCATION\\nDATE`."},
			}},
			"NormalEntry": {Name: "NormalEntry", Fields: []Field{
				{Name: "main_column", Kind: KindString, Default: "**NAME**\nSUMMARY\nHIGHLIGHTS", Description: "Template for normal entry main column. Available placeholders:\n- `NAME`: Entry name/title\n- `SUMMARY`: Summary text\n- `HIGHLIGHTS`: Bullet points list\n- `LOCATION`: Location text\n- `DATE`: Formatted date or date range\n\nYou can also add arbitrary keys to entries and use them as UPPERCASE placeholders.\n\nThe default value is `**NAME**\\nSUMMARY\\nHIGHLIGHTS`."},
				{Name: "date_and_location_column", Kind: KindString, Default: "LOCATION\nDATE", Description: "Template for normal entry date/location column. Available placeholders:\n- `NAME`: Entry name/title\n- `SUMMARY`: Summary text\n- `HIGHLIGHTS`: Bullet points list\n- `LOCATION`: Location text\n- `DATE`: Formatted date or date range\n\nYou can also add arbitrary keys to entries and use them as UPPERCASE placeholders.\n\nThe default value is `LOCATION\\nDATE`."},
			}},
			"ExperienceEntry": {Name: "ExperienceEntry", Fields: []Field{
				{Name: "main_column", Kind: KindString, Default: "**COMPANY**, POSITION\nSUMMARY\nHIGHLIGHTS", Description: "Template for experience entry main column. Available placeholders:\n- `COMPANY`: Company name\n- `POSITION`: Job title/position\n- `SUMMARY`: Summary text\n- `HIGHLIGHTS`: Bullet points list\n- `LOCATION`: Location text\n- `DATE`: Formatted date or date range\n\nYou can also add arbitrary keys to entries and use them as UPPERCASE placeholders.\n\nThe default value is `**COMPANY**, POSITION\\nSUMMARY\\nHIGHLIGHTS`."},
				{Name: "date_and_location_column", Kind: KindString, Default: "LOCATION\nDATE", Description: "Template for experience entry date/location column. Available placeholders:\n- `COMPANY`: Company name\n- `POSITION`: Job title/position\n- `SUMMARY`: Summary text\n- `HIGHLIGHTS`: Bullet points list\n- `LOCATION`: Location text\n- `DATE`: Formatted date or date range\n\nYou can also add arbitrary keys to entries and use them as UPPERCASE placeholders.\n\nThe default value is `LOCATION\\nDATE`."},
			}},
			"PublicationEntry": {Name: "PublicationEntry", Fields: []Field{
				{Name: "main_column", Kind: KindString, Default: "**TITLE**\nSUMMARY\nAUTHORS\nURL (JOURNAL)", Description: "Template for publication entry main column. Available placeholders:\n- `TITLE`: Publication title\n- `AUTHORS`: List of authors (formatted as comma-separated string)\n- `SUMMARY`: Summary/abstract text\n- `DOI`: Digital Object Identifier\n- `URL`: Publication URL (if DOI not provided)\n- `JOURNAL`: Journal/conference/venue name\n- `DATE`: Formatted date\n\nYou can also add arbitrary keys to entries and use them as UPPERCASE placeholders.\n\nThe default value is `**TITLE**\\nSUMMARY\\nAUTHORS\\nURL (JOURNAL)`."},
				{Name: "date_and_location_column", Kind: KindString, Default: "DATE", Description: "Template for publication entry date column. Available placeholders:\n- `TITLE`: Publication title\n- `AUTHORS`: List of authors (formatted as comma-separated string)\n- `SUMMARY`: Summary/abstract text\n- `DOI`: Digital Object Identifier\n- `URL`: Publication URL (if DOI not provided)\n- `JOURNAL`: Journal/conference/venue name\n- `DATE`: Formatted date\n\nYou can also add arbitrary keys to entries and use them as UPPERCASE placeholders.\n\nThe default value is `DATE`."},
			}},
			"Templates": {Name: "Templates", Fields: []Field{
				{Name: "footer", Kind: KindString, Default: "*NAME -- PAGE_NUMBER/TOTAL_PAGES*", Description: "Template for the footer. Available placeholders:\n- `NAME`: The CV owner's name from `cv.name`\n- `PAGE_NUMBER`: Current page number\n- `TOTAL_PAGES`: Total number of pages\n- `CURRENT_DATE`: Formatted date based on `design.templates.single_date`\n- `MONTH_NAME`: Full month name (e.g., January)\n- `MONTH_ABBREVIATION`: Abbreviated month name (e.g., Jan)\n- `MONTH`: Month number (e.g., 1)\n- `MONTH_IN_TWO_DIGITS`: Zero-padded month (e.g., 01)\n- `DAY`: Day of the month (e.g., 5)\n- `DAY_IN_TWO_DIGITS`: Zero-padded day (e.g., 05)\n- `YEAR`: Full year (e.g., 2025)\n- `YEAR_IN_TWO_DIGITS`: Two-digit year (e.g., 25)\n\nThe default value is `*NAME -- PAGE_NUMBER/TOTAL_PAGES*`."},
				{Name: "top_note", Kind: KindString, Default: "*LAST_UPDATED CURRENT_DATE*", Description: "Template for the top note. Available placeholders:\n- `LAST_UPDATED`: Localized \"last updated\" text from `locale.last_updated`\n- `CURRENT_DATE`: Formatted date based on `design.templates.single_date`\n- `NAME`: The CV owner's name from `cv.name`\n- `MONTH_NAME`: Full month name (e.g., January)\n- `MONTH_ABBREVIATION`: Abbreviated month name (e.g., Jan)\n- `MONTH`: Month number (e.g., 1)\n- `MONTH_IN_TWO_DIGITS`: Zero-padded month (e.g., 01)\n- `DAY`: Day of the month (e.g., 5)\n- `DAY_IN_TWO_DIGITS`: Zero-padded day (e.g., 05)\n- `YEAR`: Full year (e.g., 2025)\n- `YEAR_IN_TWO_DIGITS`: Two-digit year (e.g., 25)\n\nThe default value is `*LAST_UPDATED CURRENT_DATE*`."},
				{Name: "single_date", Kind: KindString, Default: "MONTH_ABBREVIATION YEAR", Description: "Template for single dates. Available placeholders:\n- `MONTH_NAME`: Full month name (e.g., January)\n- `MONTH_ABBREVIATION`: Abbreviated month name (e.g., Jan)\n- `MONTH`: Month number (e.g., 1)\n- `MONTH_IN_TWO_DIGITS`: Zero-padded month (e.g., 01)\n- `DAY`: Day of the month (e.g., 5)\n- `DAY_IN_TWO_DIGITS`: Zero-padded day (e.g., 05)\n- `YEAR`: Full year (e.g., 2025)\n- `YEAR_IN_TWO_DIGITS`: Two-digit year (e.g., 25)\n\nThe default value is `MONTH_ABBREVIATION YEAR`."},
				{Name: "date_range", Kind: KindString, Default: "START_DATE – END_DATE", Description: "Template for date ranges. Available placeholders:\n- `START_DATE`: Formatted start date based on `design.templates.single_date`\n- `END_DATE`: Formatted end date based on `design.templates.single_date` (or \"present\"/\"ongoing\" for current positions)\n\nThe default value is `START_DATE – END_DATE`."},
				{Name: "time_span", Kind: KindString, Default: "HOW_MANY_YEARS YEARS HOW_MANY_MONTHS MONTHS", Description: "Template for time spans (duration calculations). Available placeholders:\n- `HOW_MANY_YEARS`: Number of years (e.g., 2)\n- `YEARS`: Localized word for \"years\" from `locale.years` (or singular \"year\")\n- `HOW_MANY_MONTHS`: Number of months (e.g., 3)\n- `MONTHS`: Localized word for \"months\" from `locale.months` (or singular \"month\")\n\nThe default value is `HOW_MANY_YEARS YEARS HOW_MANY_MONTHS MONTHS`."},
				{Name: "one_line_entry", Kind: KindNested, Nested: "OneLineEntry", Description: "Template for one-line entries."},
				{Name: "education_entry", Kind: KindNested, Nested: "EducationEntry", Description: "Template for education entries."},
				{Name: "normal_entry", Kind: KindNested, Nested: "NormalEntry", Description: "Template for normal entries."},
				{Name: "experience_entry", Kind: KindNested, Nested: "ExperienceEntry", Description: "Template for experience entries."},
				{Name: "publication_entry", Kind: KindNested, Nested: "PublicationEntry", Description: "Template for publication entries."},
			}},
			"ClassicTheme": {Name: "ClassicTheme", Fields: []Field{
				{Name: "theme", Kind: KindThemeTag, Default: "classic"},
				{Name: "page", Kind: KindNested, Nested: "Page"},
				{Name: "colors", Kind: KindNested, Nested: "Colors"},
				{Name: "typography", Kind: KindNested, Nested: "Typography"},
				{Name: "links", Kind: KindNested, Nested: "Links"},
				{Name: "header", Kind: KindNested, Nested: "Header"},
				{Name: "section_titles", Kind: KindNested, Nested: "SectionTitles"},
				{Name: "sections", Kind: KindNested, Nested: "Sections"},
				{Name: "entries", Kind: KindNested, Nested: "Entries"},
				{Name: "templates", Kind: KindNested, Nested: "Templates"},
			}},
			"FontFamily": {Name: "FontFamily", Fields: []Field{
				{Name: "body", Kind: KindLiteral, Ref: "rendercv__schema__models__design__font_family__FontFamily", Members: FontFamilies, Default: "Source Sans 3", Description: "The font family for body text. The default value is `Source Sans 3`."},
				{Name: "name", Kind: KindLiteral, Ref: "rendercv__schema__models__design__font_family__FontFamily", Members: FontFamilies, Default: "Source Sans 3", Description: "The font family for the name. The default value is `Source Sans 3`."},
				{Name: "headline", Kind: KindLiteral, Ref: "rendercv__schema__models__design__font_family__FontFamily", Members: FontFamilies, Default: "Source Sans 3", Description: "The font family for the headline. The default value is `Source Sans 3`."},
				{Name: "connections", Kind: KindLiteral, Ref: "rendercv__schema__models__design__font_family__FontFamily", Members: FontFamilies, Default: "Source Sans 3", Description: "The font family for connections. The default value is `Source Sans 3`."},
				{Name: "section_titles", Kind: KindLiteral, Ref: "rendercv__schema__models__design__font_family__FontFamily", Members: FontFamilies, Default: "Source Sans 3", Description: "The font family for section titles. The default value is `Source Sans 3`."},
			}},
		},
	}
}
