package templater

import (
	"embed"
	"io/fs"
)

// Builtin is the transformed template tree, generated by `tools/gentemplates`
// from the submodule and embedded so the binary needs no template files at
// runtime.
//
// **Never hand-edited.** `just gentemplates` regenerates it; a manual change is
// lost on the next run and, worse, would make the generated source stop matching
// upstream's without anything saying so.
//
//go:embed templates
var Builtin embed.FS

// BuiltinTemplates is Builtin rooted at `templates/`, which is the path shape
// Loader expects — `typst/Header.j2.typ` rather than
// `templates/typst/Header.j2.typ`.
func BuiltinTemplates() fs.FS {
	sub, err := fs.Sub(Builtin, "templates")
	if err != nil {
		// Unreachable: the directory is embedded at compile time, so a failure
		// here means the embed pattern matched nothing — a build-time mistake
		// that would have failed the build.
		panic("templater: embedded templates are missing: " + err.Error())
	}
	return sub
}
