// Command cellprobe captures Rich's unicode width data — the table behind
// `rich.cells.cell_len` — into internal/cli/celltable.go.
//
// **The table is data, not logic.** It is 464 codepoint spans plus the 213
// characters a variation selector widens, and transcribing it by hand would be
// a golden by another name (AGENTS.md §10.1). This asks the vendored Rich for
// it, so a submodule bump — or a Rich upgrade under it — moves the port's
// widths with upstream's instead of leaving them quietly stale.
//
// What it captures is `rich._unicode_data.load("latest").cell_table`, which is
// what `cell_len(text, "auto")` resolves to when `UNICODE_VERSION` is unset.
//
// GENERATED, never hand-edited; regenerate with `just cellprobe`.
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"strings"
)

const (
	upstreamDir = "third_party/rendercv"
	outPath     = "internal/cli/celltable.go"
)

const cellTableScript = `
import json

from rich._unicode_data import load

table = load("latest")
print(json.dumps({
    "unicode_version": table.unicode_version,
    "widths": [list(span) for span in table.widths],
    "narrow_to_wide": sorted(ord(character) for character in table.narrow_to_wide),
}))
`

// cellTable is what the script above prints.
type cellTable struct {
	UnicodeVersion string   `json:"unicode_version"`
	Widths         [][3]int `json:"widths"`
	NarrowToWide   []int    `json:"narrow_to_wide"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "cellprobe: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	command := exec.Command("uv", "run", "--frozen", "--all-extras", "python", "-c", cellTableScript)
	command.Dir = upstreamDir
	command.Stderr = os.Stderr

	out, err := command.Output()
	if err != nil {
		return fmt.Errorf("running uv (is the submodule initialized? `just setup`): %w", err)
	}

	var table cellTable
	if err := json.Unmarshal(out, &table); err != nil {
		return fmt.Errorf("upstream did not print JSON: %w", err)
	}
	if len(table.Widths) == 0 || len(table.NarrowToWide) == 0 {
		return fmt.Errorf("upstream printed an empty table: %s", out)
	}

	// Through go/format, so the committed file is what `just check` expects
	// rather than what this tool happened to print.
	source, err := format.Source([]byte(render(table)))
	if err != nil {
		return fmt.Errorf("generated source does not parse: %w", err)
	}
	if err := os.WriteFile(outPath, source, 0o644); err != nil { //nolint:gosec // committed source
		return err
	}
	fmt.Printf("wrote %s (%d spans, %d narrow-to-wide, unicode %s)\n",
		outPath, len(table.Widths), len(table.NarrowToWide), table.UnicodeVersion)
	return nil
}

func render(table cellTable) string {
	var out strings.Builder
	fmt.Fprintf(&out, `// Code generated by tools/cellprobe; DO NOT EDIT.
//
// Rich's unicode width data, captured from
// %[1]s at unicode %[2]s
// (%[3]s spans, %[4]s narrow-to-wide characters).

package cli

// cellTableUnicodeVersion is the unicode revision these widths came from.
const cellTableUnicodeVersion = %[2]q

// cellWidths is rich's CellTable.widths: sorted, non-overlapping spans of
// codepoints, each with the number of columns its members occupy.
var cellWidths = [...]cellSpan{
`, "rich._unicode_data", table.UnicodeVersion,
		fmt.Sprint(len(table.Widths)), fmt.Sprint(len(table.NarrowToWide)))

	for _, span := range table.Widths {
		fmt.Fprintf(&out, "\t{0x%04X, 0x%04X, %d},\n", span[0], span[1], span[2])
	}

	out.WriteString(`}

// narrowToWide is rich's CellTable.narrow_to_wide: the characters a following
// variation selector 16 promotes from one column to two.
var narrowToWide = map[rune]struct{}{
`)
	for _, codepoint := range table.NarrowToWide {
		fmt.Fprintf(&out, "\t0x%04X: {},\n", codepoint)
	}
	out.WriteString("}\n")
	return out.String()
}
