// Command designprobe generates the design subsystem's data from the submodule.
//
// **Generated, not transcribed**, for the reason `tools/localeprobe` states and
// which is stronger here: `classic_theme.py` is 857 lines declaring twenty-two
// nested models whose descriptions run to hundreds of bytes and list template
// placeholders line by line, and `pydantic_extra_types` carries 147 CSS colour
// names. A typo in any of them is invisible to review and reports as one of 161
// byte failures in the `$defs` differential.
//
// **What this costs, stated plainly**, is `tools/localeprobe`'s cost twice over:
//
//   - the submodule-diff test compares the generated data against the same
//     source it was generated from, so it cannot fail at generation time. Its
//     value is drift detection after a submodule bump, not transcription
//     checking.
//   - the colour names come from **introspecting the installed
//     `pydantic_extra_types`**, not from a file in the submodule, so what they
//     are pinned against is a resolved dependency version. `uv.lock` is what
//     makes that reproducible; nothing in the Go tree can check it.
//
// The tool needs `uv` and an initialized submodule, which makes it a
// `just`-gated tool like `gengolden` rather than something `go generate` runs.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// submodule is the vendored Python, relative to the repository root.
const submodule = "third_party/rendercv"

// colorNamesScript prints the library's colour table as JSON.
//
// `COLORS_BY_NAME` maps a name to an `(r, g, b)` tuple. The names are what
// `Color("red")` accepts, matched **case-insensitively** — which is why the Go
// table is keyed by the lowercase name and the probe asserts the source is
// already lowercase rather than lowercasing silently.
const colorNamesScript = `
import json
from pydantic_extra_types.color import COLORS_BY_NAME
print(json.dumps(COLORS_BY_NAME, sort_keys=True))
`

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "designprobe: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := repositoryRoot()
	if err != nil {
		return err
	}

	colors, err := colorNames(root)
	if err != nil {
		return fmt.Errorf("reading the colour table: %w", err)
	}

	target := filepath.Join(root, "internal", "schema", "models", "design", "colornames_generated.go")
	return os.WriteFile(target, renderColorNames(colors), 0o644)
}

// repositoryRoot walks up from the working directory to the module root, so the
// tool can be run from anywhere.
func repositoryRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod above %s", dir)
		}
		dir = parent
	}
}

type rgb struct{ R, G, B int }

func colorNames(root string) (map[string]rgb, error) {
	command := exec.Command("uv", "run", "--frozen", "--all-extras", "python", "-c", colorNamesScript)
	command.Dir = filepath.Join(root, submodule)
	command.Stderr = os.Stderr

	out, err := command.Output()
	if err != nil {
		return nil, fmt.Errorf("running uv (is the submodule initialized? `just setup`): %w", err)
	}

	var raw map[string][3]int
	if err := json.Unmarshal(out, &raw); err != nil {
		return nil, err
	}
	if len(raw) == 0 {
		return nil, fmt.Errorf("the colour table is empty")
	}

	names := make(map[string]rgb, len(raw))
	for name, value := range raw {
		if name != strings.ToLower(name) {
			return nil, fmt.Errorf("colour name %q is not lowercase; the Go table assumes it is", name)
		}
		names[name] = rgb{value[0], value[1], value[2]}
	}
	return names, nil
}

func renderColorNames(colors map[string]rgb) []byte {
	names := make([]string, 0, len(colors))
	for name := range colors {
		names = append(names, name)
	}
	sort.Strings(names)

	var out strings.Builder
	out.WriteString(`// Code generated by tools/designprobe. DO NOT EDIT.

package design

// colorNames is ` + "`COLORS_BY_NAME`" + ` from pydantic_extra_types, the CSS colour
// keywords ` + "`Color`" + ` accepts by name.
//
// Generated rather than transcribed: ` + fmt.Sprint(len(names)) + ` entries whose values are not
// checkable by eye. What pins them is a resolved dependency version rather than
// a file in the submodule — see tools/designprobe for what that guarantee is and
// is not.
//
// Keyed lowercase. Upstream matches a name case-insensitively, so the lookup
// lowercases first.
var colorNames = map[string]colorRGB{
`)
	for _, name := range names {
		value := colors[name]
		fmt.Fprintf(&out, "\t%q: {%d, %d, %d},\n", name, value.R, value.G, value.B)
	}
	out.WriteString("}\n")
	return []byte(out.String())
}
