//go:build conformance

package sample

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"github.com/nonamecat19/rendercv-go/internal/version"
)

const (
	upstreamDir = "../../../third_party/rendercv"
	interpreter = upstreamDir + "/.venv/bin/python"
	driver      = "testdata/upstream.py"
)

// upstream is testdata/upstream.py's output: every starter CV the vendored
// Python emits, generated by this test run rather than captured earlier.
type upstream struct {
	Version   string            `json:"version"`
	Themes    []string          `json:"themes"`
	Locales   []string          `json:"locales"`
	Documents map[string]string `json:"documents"`
	Names     []struct {
		Name   string `json:"name"`
		Region string `json:"region"`
	} `json:"names"`
}

var (
	once   sync.Once
	shared upstream
	loaded error
)

// load runs the driver once per test binary. It costs about five seconds — one
// interpreter start plus 198 model builds — and every test below shares it.
func load(t *testing.T) upstream {
	t.Helper()
	once.Do(func() {
		// The submodule's own interpreter, by path: `uv run … rendercv` from
		// outside the submodule resolves to whatever is on PATH.
		cmd := exec.Command(mustAbs(t, interpreter), mustAbs(t, driver))
		cmd.Dir = mustAbs(t, upstreamDir)
		cmd.Stderr = os.Stderr
		out, err := cmd.Output()
		if err != nil {
			loaded = err
			return
		}
		loaded = json.Unmarshal(out, &shared)
	})
	if loaded != nil {
		t.Fatalf("drive the vendored rendercv: %v", loaded)
	}
	return shared
}

func mustAbs(t *testing.T, path string) string {
	t.Helper()
	absolute, err := filepath.Abs(path)
	if err != nil {
		t.Fatal(err)
	}
	return absolute
}

// TestGenerateMatrix is spec 013 §8's first acceptance criterion: for every one
// of the 9 x 22 theme/locale pairs, the document the port generates is
// byte-identical to the one upstream generates, final byte included.
//
// The comparison is against a live process, not against a digest of a past
// capture: upstream changing its dump fails this the next time it runs, which
// is what the criterion is for. It is also why the whole text crosses the
// boundary rather than an md5 — a mismatch has to print something a reader can
// act on.
func TestGenerateMatrix(t *testing.T) {
	u := load(t)
	if got, want := len(u.Documents), len(u.Themes)*len(u.Locales); got != want {
		t.Fatalf("upstream produced %d documents, want %d", got, want)
	}
	if len(u.Documents) == 0 {
		t.Fatal("upstream produced no documents")
	}
	for _, theme := range u.Themes {
		for _, locale := range u.Locales {
			t.Run(theme+"/"+locale, func(t *testing.T) {
				want, ok := u.Documents[theme+"/"+locale]
				if !ok {
					t.Fatal("upstream produced no document for this pair")
				}
				got, err := Generate("John Doe", theme, locale)
				if err != nil {
					t.Fatal(err)
				}
				if got != want {
					t.Errorf("the documents differ at %s", firstDifference(got, want))
				}
			})
		}
	}
}

// firstDifference locates a byte mismatch for the failure message: the whole
// document is two thousand lines and printing both is unreadable.
func firstDifference(got, want string) string {
	gotLines := strings.SplitAfter(got, "\n")
	wantLines := strings.SplitAfter(want, "\n")
	for i := range min(len(gotLines), len(wantLines)) {
		if gotLines[i] != wantLines[i] {
			return fmt.Sprintf("line %d:\n  port     = %q\n  upstream = %q",
				i+1, gotLines[i], wantLines[i])
		}
	}
	return fmt.Sprintf("line %d: the port has %d lines, upstream has %d",
		min(len(gotLines), len(wantLines))+1, len(gotLines), len(wantLines))
}

// TestGenerateVersion pins the constant to the running submodule: a bump that
// moves upstream's `__version__` without moving ours would otherwise show up as
// 198 identical document failures with no explanation.
func TestGenerateVersion(t *testing.T) {
	if got := load(t).Version; got != version.RenderCV {
		t.Errorf("upstream is v%s, internal/version says v%s", got, version.RenderCV)
	}
}

// TestNameLine is spec 013 §8's name criterion and §3.1 behavior 7's table: for
// each name in the driver's battery, the exact `cv.name` region upstream emits.
// Every style the emitter can pick is in there, along with the resolver cases
// that force a quote and the escapes that force the double-quoted writer.
//
// The comparison runs through `Generate` rather than through `nameLine`
// directly, because the region is not the emitter's output alone: a name that
// becomes a literal block contributes lines to the document like any other, and
// a continuation line shaped like a list item goes through the nested-bullet
// regex (`schema/sample_generator.py:151-159`) on its way out.
func TestNameLine(t *testing.T) {
	battery := load(t).Names
	if len(battery) == 0 {
		t.Fatal("the name battery is empty")
	}
	for _, c := range battery {
		t.Run(c.Name, func(t *testing.T) {
			document, err := Generate(c.Name, "classic", "english")
			if err != nil {
				t.Fatal(err)
			}
			if got := nameRegion(t, document); got != c.Region {
				t.Errorf("name %q rendered as\n%q\nupstream =\n%q", c.Name, got, c.Region)
			}
		})
	}
}

// nameRegion is the slice of a generated document that holds `cv.name` — from
// just after `cv:` to just before `headline:`, `Cv`'s next field. It is the same
// cut testdata/upstream.py makes on the other side.
func nameRegion(t *testing.T, document string) string {
	t.Helper()
	start := strings.Index(document, "cv:\n")
	if start < 0 {
		t.Fatal("the document has no cv block")
	}
	start += len("cv:\n")
	end := strings.Index(document[start:], "\n  headline:")
	if end < 0 {
		t.Fatal("the cv block has no headline field")
	}
	return document[start : start+end+1]
}

// TestNewWritesTheGeneratedDocument bridges the two levels: the battery above
// calls `create_sample_yaml_input_file` in process, and `new` is what a user
// runs. This runs upstream's CLI in a scratch directory outside the repository
// and checks that the file it writes — name and bytes — is what the battery
// said it would be. One pair is enough; the CLI does not vary with the axes,
// and 198 interpreter starts cost two minutes where the battery costs five
// seconds.
func TestNewWritesTheGeneratedDocument(t *testing.T) {
	u := load(t)

	dir := t.TempDir()
	cmd := exec.Command(
		mustAbs(t, upstreamDir+"/.venv/bin/rendercv"),
		"new", "John Doe", "--theme", "classic", "--locale", "english",
	)
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("upstream new failed: %v\n%s", err, out)
	}

	name := FileName("John Doe")
	written, err := os.ReadFile(filepath.Join(dir, name))
	if err != nil {
		t.Fatalf("upstream wrote no %s: %v", name, err)
	}
	if string(written) != u.Documents["classic/english"] {
		t.Error("upstream's CLI wrote a document the generator battery does not have")
	}

	generated, err := Generate("John Doe", "classic", "english")
	if err != nil {
		t.Fatal(err)
	}
	if generated != string(written) {
		t.Errorf("the port's document differs from the file upstream's CLI wrote at %s",
			firstDifference(generated, string(written)))
	}
}
