package process_test

// classERemainder is spec 011-E §3's emphasis class, landed as fixture rows
// before the fix that closes it (`AGENTS.md` §7: fixtures first, red).
//
// Every one of these 98 shapes is a row in **both** `testdata/html.json` and
// `testdata/markdown_to_typst.json`, generated by `tools/mdprobe` from the
// vendored library, and every one of them still differs here. The two
// differentials disagree with upstream on exactly the same set, which is what
// says the cause is shared: two character-class predicates, not two parsers.
//
// The cause, measured in §3 and re-measured before this file was written:
// `isSpaceByte` is Python's `\s` short by 23 codepoints, so `NOT_STRONG_RE`
// fails to eat a delimiter run beside `\xa0`; and `isWordByte` counts every
// byte ≥ 0x80 as a word byte, so `SMART_*_RE`'s `(?<!\w)` refuses to open
// beside `·` or `—`. The two push opposite ways — 69 rows here emphasise where
// upstream does not, 27 refuse where upstream does — and the last two are
// §3.3's reachable case, the non-breaking space a word processor leaves in
// pasted text.
//
// The pins are **inverted**: a shape in this list that starts matching fails
// the suite, for the reason `conformance.AssertUnreachable` gives — a
// tolerated-mismatch list that cannot notice being fixed is a mute button. The
// list goes away wholesale with the fix; it is not a divergence and nothing in
// `specs/divergences.md` covers it.
var classERemainder = map[string]bool{
	"**\x1cb**":                   true,
	"**b\x1c** x":                 true,
	"a **\x1c** b":                true,
	"**\x1db**":                   true,
	"**b\x1d** x":                 true,
	"a **\x1d** b":                true,
	"**\x1eb**":                   true,
	"**b\x1e** x":                 true,
	"a **\x1e** b":                true,
	"**\x1fb**":                   true,
	"**b\x1f** x":                 true,
	"a **\x1f** b":                true,
	"**\u0085b**":                 true,
	"**b\u0085** x":               true,
	"a **\u0085** b":              true,
	"**\u00a0b**":                 true,
	"**b\u00a0** x":               true,
	"a **\u00a0** b":              true,
	"**\u1680b**":                 true,
	"**b\u1680** x":               true,
	"a **\u1680** b":              true,
	"**\u2000b**":                 true,
	"**b\u2000** x":               true,
	"a **\u2000** b":              true,
	"**\u2001b**":                 true,
	"**b\u2001** x":               true,
	"a **\u2001** b":              true,
	"**\u2002b**":                 true,
	"**b\u2002** x":               true,
	"a **\u2002** b":              true,
	"**\u2003b**":                 true,
	"**b\u2003** x":               true,
	"a **\u2003** b":              true,
	"**\u2004b**":                 true,
	"**b\u2004** x":               true,
	"a **\u2004** b":              true,
	"**\u2005b**":                 true,
	"**b\u2005** x":               true,
	"a **\u2005** b":              true,
	"**\u2006b**":                 true,
	"**b\u2006** x":               true,
	"a **\u2006** b":              true,
	"**\u2007b**":                 true,
	"**b\u2007** x":               true,
	"a **\u2007** b":              true,
	"**\u2008b**":                 true,
	"**b\u2008** x":               true,
	"a **\u2008** b":              true,
	"**\u2009b**":                 true,
	"**b\u2009** x":               true,
	"a **\u2009** b":              true,
	"**\u200ab**":                 true,
	"**b\u200a** x":               true,
	"a **\u200a** b":              true,
	"**\u2028b**":                 true,
	"**b\u2028** x":               true,
	"a **\u2028** b":              true,
	"**\u2029b**":                 true,
	"**b\u2029** x":               true,
	"a **\u2029** b":              true,
	"**\u202fb**":                 true,
	"**b\u202f** x":               true,
	"a **\u202f** b":              true,
	"**\u205fb**":                 true,
	"**b\u205f** x":               true,
	"a **\u205f** b":              true,
	"**\u3000b**":                 true,
	"**b\u3000** x":               true,
	"a **\u3000** b":              true,
	"a\u0085_b_ c":                true,
	"a\u00a0_b_ c":                true,
	"a\u1680_b_ c":                true,
	"a\u2000_b_ c":                true,
	"a\u2001_b_ c":                true,
	"a\u2002_b_ c":                true,
	"a\u2003_b_ c":                true,
	"a\u2004_b_ c":                true,
	"a\u2005_b_ c":                true,
	"a\u2006_b_ c":                true,
	"a\u2007_b_ c":                true,
	"a\u2008_b_ c":                true,
	"a\u2009_b_ c":                true,
	"a\u200a_b_ c":                true,
	"a\u2028_b_ c":                true,
	"a\u2029_b_ c":                true,
	"a\u202f_b_ c":                true,
	"a\u205f_b_ c":                true,
	"a\u3000_b_ c":                true,
	"\u00b7_x_":                   true,
	"_x_\u00b7":                   true,
	"\u2014_x_":                   true,
	"_x_\u2014":                   true,
	"\u00b7__x__":                 true,
	"__x__\u2014":                 true,
	"\u20ac_x_":                   true,
	"_x_\u00a9":                   true,
	"**\u00a0Senior Engineer**":   true,
	"**Team lead\u00a0** at ACME": true,
}
