//go:build conformance

package process_test

import (
	"encoding/json"
	"testing"

	"github.com/nonamecat19/rendercv-go/internal/conformance"
	"github.com/nonamecat19/rendercv-go/internal/renderer/templater/process"
)

// Differential against python-markdown, now 256 shapes and growing. The
// fixture is CPython's own output, generated through the vendored submodule's
// `markdown.markdown` — never hand-written (`AGENTS.md` §10.1).
//
// **The 75-row version of this fixture was the reason the port believed it was
// nearly done.** A fresh-context verifier found eight further divergence classes
// reachable from an ordinary CV highlight, none of them represented here and none
// recorded as a divergence; the rows below were added first, red, and the fixes
// followed one class per commit. Six of the eight closed, together with five more
// classes the reproduction turned up on the way — tab expansion, code-span
// newlines, URL escaping, line-break rules, and whitespace at the end of a block.
// Iteration 11's Wave C (spec §7-8) added the emphasis and link-destination
// classes, then 17 more rows pinning a regression a fresh-context verifier
// found in Wave C's own first pass.
//
// **A second fresh-context verifier then measured 147 shapes that Wave C had
// broken and no fixture could see**, 124 of them one class: a delimiter run
// flanked by whitespace. The 35 rows at the end of this file pin all six
// classes it reported, and the mechanism they forced —
// resolving every pattern registered above `em_strong` before the emphasis
// matchers ever run — is `stash.go`'s `maskAbove`. Both verdicts came from a
// green suite, which is the whole argument for the differential being wide.
//
// A third verifier then found a panic and 300 more regressions, and a fourth
// round closed the registry-priority rule for the two emphasis processors.
//
// A fifth then measured spec 011-E's emphasis class — a delimiter run beside a
// **non-ASCII** space or non-word rune, which zero of the 761 rows put in front
// of a delimiter and so no differential could see. Its 103 shapes are the rows
// at the end of this file and of the Typst fixture, generated by
// `tools/mdprobe`; all 103 now match, on both backends, since `pyclass.go`
// gave the emphasis guards Python's own `\w` and `\s`.
//
// A sixth measured spec 011-A's ATX class — a hash run with no space after it,
// indented, longer than six, or closed by a bare run. None of the 761 rows and
// none of the golden corpus's 298 hash-initial lines was in any divergent
// class, so neither gate could see it either.
//
// A seventh enumerated spec 011 §9.5's block-tag-in-a-container class, which
// one pinned row had stood for since iteration 11 and which turned out to be 22
// of 33 shapes. `htmlblock.go`'s `atLineStart` closed 18 and the key left
// `knownRemainder`.
//
// An eighth enumerated 42 raw-block adjacencies — a raw block with **another
// block after it**, which no row had carried — and 29 differed, in two classes.
// The first, a blank line between the two, is `htmlblock.go`'s
// `htmlBlockRenderer`. The second was a raw block with **no** blank line after
// its closing tag, where upstream ends the block anyway
// (`htmlparser.py:240-253`) and goldmark runs on to the next blank line: its 9
// rows, and the one row of it the Typst fixture reaches, are closed by
// `blockLevelHTMLParser.Continue` and `splitRawBlockTails`.
//
// A ninth took the last container shape, `- <div>\nmulti\n</div>`, which had
// been recorded as needing a scanner over the block's whole text and did not:
// upstream never opens a raw block on a **closing** tag (`htmlparser.py:230-255`
// against `:215`), so the `</div>` that was leaving the `<li>` had no block to
// leave into. 63 rows enumerate the rule, and a lone `</div>` reaches
// `RawHtmlPostprocessor`'s `<p>`-stripping (`postprocessors.py:84-86`), which is
// `postprocessors.go`.
//
// Measured after that work: 2 rows differ in `knownRemainder` and 3 in
// `containerBlockTag`, checked by running `MarkdownToHTML` over every `In` and
// diffing against the fixture's `Out` — not read off a commit message.
//
// It lives behind the conformance tag because it needs no upstream process but
// does encode upstream's exact output.
// **An absent fixture fails this test rather than skipping it.** It used to
// skip, which meant the whole differential could leave `just test-parity`
// without changing a single character of its output —
// `conformance.RequireInput` makes the fixture's absence loud, with the shared
// opt-out for someone who deliberately has not generated it
// (`internal/conformance/requireinput.go`).
func TestMarkdownToHTMLMatchesPython(t *testing.T) {
	raw := conformance.RequireInput(t, "testdata/html.json",
		"the python-markdown differential",
		"regenerate it through the vendored submodule's `markdown.markdown` (AGENTS.md §10.1)")
	var rows []struct{ In, Out string }
	if err := json.Unmarshal(raw, &rows); err != nil {
		t.Fatal(err)
	}
	for _, row := range rows {
		got, err := process.MarkdownToHTML(row.In)
		if err != nil {
			t.Fatalf("%q: %v", row.In, err)
		}
		if _, known := knownRemainder[row.In]; known || containerBlockTag[row.In] {
			// Inverted, for the same reason conformance.AssertUnreachable is:
			// a list of tolerated mismatches that does not notice being fixed
			// becomes a mute button.
			if got == row.Out {
				t.Errorf("MarkdownToHTML(%q) now matches python-markdown"+
					" — remove it from whichever of knownRemainder"+
					" or containerBlockTag holds it", row.In)
			}
			continue
		}
		if got != row.Out {
			t.Errorf("MarkdownToHTML(%q)\n = %q\nwant %q", row.In, got, row.Out)
		}
	}
}

// knownRemainder is what still differs after Wave C (spec 011 §7-8, T8-T12):
// one shape spec §9.3 declines on purpose, and one class nobody has taken.
// Each is pinned by an **inverted** assertion above —
// the case still runs, still has to produce output, and still has to differ —
// for the same reason `conformance.AssertUnreachable` is: a list of tolerated
// mismatches that cannot notice being fixed is a mute button.
//
// Neither is recorded in `specs/divergences.md`; spec 011 §9.4 argues neither is parity-impossible.
//
//  1. **A destination spanning a line break.** `getLink` scans the block's
//     whole text, so `[t](a\nb)` upstream is one link with a literal newline
//     in its `href`; matching that needs a block-level scanner. Spec 011 §9.3.
//  2. **A tag name with a dot in it.** `<stdio.h>` is raw inline HTML to
//     python-markdown's `HTMLExtractor` and is passed through; CommonMark 0.31
//     §6.6 spells a tag name `[A-Za-z][A-Za-z0-9-]*`, so goldmark reads the
//     `.` as ordinary text and escapes the angle brackets. **Nothing to do with
//     headings** — `a <stdio.h> b`, `<stdio.h>` and `a <b.c> d` differ the same
//     way in a plain paragraph, measured. The row below is the ATX shape of it
//     that spec-delta-atx §3.2 pinned, and the class has no owner yet.
var knownRemainder = map[string]string{
	"[t](a\nb)":          "spec 011 §9.3: a destination spanning a line break is out of scope, declined permanently",
	"#include <stdio.h>": "a dotted tag name is raw HTML upstream and text in CommonMark; not the ATX rule",
}
