settings:
  current_date: today
  render_command:
    output_folder: rendercv_output
    design:
    locale:
    typst_path: OUTPUT_FOLDER/NAME_IN_SNAKE_CASE_CV.typ
    pdf_path: OUTPUT_FOLDER/NAME_IN_SNAKE_CASE_CV.pdf
    markdown_path: OUTPUT_FOLDER/NAME_IN_SNAKE_CASE_CV.md
    html_path: OUTPUT_FOLDER/NAME_IN_SNAKE_CASE_CV.html
    png_path: OUTPUT_FOLDER/NAME_IN_SNAKE_CASE_CV.png
    dont_generate_markdown: false
    dont_generate_html: false
    dont_generate_typst: false
    dont_generate_pdf: false
    dont_generate_png: false
  bold_keywords: []
  pdf_title: NAME - CV
